
<?php echo $this->getContent(); ?>

<?php echo $this->tag->form("users/save") ?>

<table width="100%">
    <tr>
        <td align="left"><?php echo $this->tag->linkTo(array("users", "Back")) ?></td>
        <td align="right"><?php echo $this->tag->submitButton("Save") ?></td>
    </tr>
</table>

<div align="center">
    <h1>Edit users</h1>
</div>

<table>
    <tr>
        <td align="right">
            <label for="first_name">First Of Name</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("first_name", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="last_name">Last Of Name</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("last_name", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="email">Email</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("email", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="password">Password</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("password", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="telephone">Telephone</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("telephone", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="gender">Gender</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("gender", "type" => "number")) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="address">Address</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("address", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="modified">Modified</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("modified", "size" => 30)) ?>
        </td>
    </tr>
    <tr>
        <td align="right">
            <label for="created">Created</label>
        </td>
        <td align="left">
            <?php echo $this->tag->textField(array("created", "size" => 30)) ?>
        </td>
    </tr>

    <tr>
        <td><?php echo $this->tag->hiddenField("id") ?></td>
        <td><?php echo $this->tag->submitButton("Save") ?></td>
    </tr>
</table>

</form>
